version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-ticketflow
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # ADM interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistence of RabbitMQ Data
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:13
    container_name: db-ticketflow
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db_data:/var/lib/postgresql/data # Persistence of PostgreSQL Data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
  db_data: